server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/chen-c12/springcloud-config.git #ssh地址或http地址
          search-paths:
#            - springcloud-config
            - thymeleaf
          uri: https://gitee.com/chen-www/thymeleaf.git
      label: master  #分支

  rabbitmq:
    host: 192.168.184.150
    port: 5672
    username: guest
    password: guest



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka

#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints: #暴露刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'