server:
  port: 8004
spring:
  application:
    name: cloud-provider-payment

  cloud:
    zookeeper:
      connect-string: 192.168.184.140:2181


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2022?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.chenddd.springcloud.entities

